float64 orientation # Rack's orientation (and thus expected final orientation of the robot)
string rack_no
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages
