name: Remote Slot Testing Setup
on:
  push:
    tags:
      - 'slot*'

jobs:
  setup-branch:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            cl2703
            ebot_docking


      - run: git config --global user.email "vedanthpadmaraman0566@gmail.com"
      - run: git config --global user.name "GlowingScrewdriver (Automated)"

      - run: git branch remote_access
      - run: git switch remote_access

      - run: git add .
      - run: git commit -m "Slot bringup"
      - run: git push --branches remote_access
